"""add avatar_url to users

Revision ID: 358966d568f9
Revises: 75347140f394
Create Date: 2026-02-19 23:00:44.817002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '358966d568f9'
down_revision: Union[str, None] = '75347140f394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('wallets', sa.Column('last_4', sa.String(length=4), nullable=True))
    op.add_column('wallets', sa.Column('total_limit', sa.Float(), nullable=True))
    op.add_column('wallets', sa.Column('bill_date', sa.Integer(), nullable=True))
    op.add_column('wallets', sa.Column('due_date', sa.Integer(), nullable=True))
    op.add_column('wallets', sa.Column('additional_charges', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'additional_charges')
    op.drop_column('wallets', 'due_date')
    op.drop_column('wallets', 'bill_date')
    op.drop_column('wallets', 'total_limit')
    op.drop_column('wallets', 'last_4')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
